### ISSUE TITLE
Косяк!

### ISSUE THREAD

**Issue by denver411** [MiMisar/HomeWork6#3]
https://github.com/MiMisar/HomeWork6/blob/c8f559fc28184aedfe28c83fa7f1b9f54af59be7/style.css#L88

По условиям "первый дочерний блок должен в ширину 250 пикселей, а другой занимал все **оставшееся** место, вне зависимости от ширины окна"
У тебя правый блок растягивается на всю ширину родителя и заползает также на левый блок

**Comment by MiMisar** [comment]
Ааа, т.е. эти элементы должны оставаться один сверху, а другой снизу, как изначально? Просто верхний в размере 250рх?

**Comment by denver411** [comment]
Нет. Один слева, другой справа

**Comment by MiMisar** [comment]
Понял, проверю дома.

**Comment by MiMisar** [comment]
Точно, косяк. Не заметил, что второй на всю ширину расположился =(

**Comment by denver411** [comment]
Теперь хорошо
